[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
crc = "3"
rxing = "0.9"
thiserror = "2"
qrcodegen = "1.8"
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[package.metadata.component]
package = "component:protocol"

[package.metadata.component.dependencies]
